MOCK_PRODUCTS = [
    {
        "sku": "SUP-001",
        "name": "Suporte Veicular Para Celular",
        "description": "Suporte universal para celular com fixação no painel. Ideal para motoristas de aplicativo.",
        "cost_price": 22.90,
        "stock": 50,
        "weight_kg": 0.25,
        "height_cm": 8,
        "width_cm": 12,
        "length_cm": 15,
        "category": "Acessórios Automotivos",
        "brand": "MockAuto",
        "ean": "7890000000011",
        "image_url": "https://via.placeholder.com/600x600.png?text=Produto+001"
    },
    {
        "sku": "SUP-002",
        "name": "Cabo USB-C Reforçado 1 Metro",
        "description": "Cabo USB-C para carregamento rápido, ideal para celulares Android.",
        "cost_price": 9.90,
        "stock": 120,
        "weight_kg": 0.10,
        "height_cm": 2,
        "width_cm": 8,
        "length_cm": 12,
        "category": "Acessórios para Celular",
        "brand": "MockTech",
        "ean": "7890000000028",
        "image_url": "https://via.placeholder.com/600x600.png?text=Produto+002"
    },
    {
        "sku": "SUP-003",
        "name": "Organizador Multiuso Para Cozinha",
        "description": "Organizador plástico para armário, cozinha, banheiro e lavanderia.",
        "cost_price": 18.50,
        "stock": 80,
        "weight_kg": 0.45,
        "height_cm": 10,
        "width_cm": 20,
        "length_cm": 30,
        "category": "Casa e Organização",
        "brand": "MockCasa",
        "ean": "7890000000035",
        "image_url": "https://via.placeholder.com/600x600.png?text=Produto+003"
    },
    {
        "sku": "SUP-004",
        "name": "Kit 3 Panos de Microfibra",
        "description": "Kit com 3 panos multiuso para limpeza automotiva e doméstica.",
        "cost_price": 12.80,
        "stock": 200,
        "weight_kg": 0.20,
        "height_cm": 3,
        "width_cm": 18,
        "length_cm": 25,
        "category": "Casa e Limpeza",
        "brand": "MockClean",
        "ean": "7890000000042",
        "image_url": "https://via.placeholder.com/600x600.png?text=Produto+004"
    },
    {
        "sku": "SUP-005",
        "name": "Tapete Higiênico Pet 30 Unidades",
        "description": "Tapete higiênico absorvente para cães de pequeno e médio porte.",
        "cost_price": 39.90,
        "stock": 35,
        "weight_kg": 1.10,
        "height_cm": 12,
        "width_cm": 25,
        "length_cm": 35,
        "category": "Pet",
        "brand": "MockPet",
        "ean": "7890000000059",
        "image_url": "https://via.placeholder.com/600x600.png?text=Produto+005"
    }
]
