def btn(url, label):
    if not url:
        return ""
    return f"<a class='btn' href='{url}'>{label}</a>"

def shell(title, content):
    return f"""<!doctype html><html lang='pt-BR'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>{title}</title>
<style>
body{{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f4f7fb;color:#111827}} aside{{position:fixed;left:0;top:0;bottom:0;width:250px;background:#0b1220;color:white;padding:20px;overflow:auto}} aside a{{display:block;color:white;text-decoration:none;padding:9px;border-radius:8px;margin:4px 0}} aside a:hover{{background:#172033}} main{{margin-left:270px;padding:28px}} .grid{{display:grid;grid-template-columns:repeat(4,minmax(160px,1fr));gap:14px}} .card,.metric{{background:white;border:1px solid #d8dee8;border-radius:14px;padding:18px;margin:14px 0;box-shadow:0 8px 24px rgba(15,23,42,.05)}} .metric span{{display:block;color:#64748b}} .metric strong{{font-size:24px}} .btn{{display:inline-block;background:#2563eb;color:white;text-decoration:none;padding:10px 14px;border-radius:10px;margin:6px 5px 6px 0}} input{{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;margin:5px 0 12px}} button{{background:#2563eb;color:white;border:0;padding:10px 14px;border-radius:10px}} table{{width:100%;border-collapse:collapse;background:white}} th,td{{border-bottom:1px solid #e5e7eb;text-align:left;padding:10px}} th{{background:#f8fafc}} pre{{background:#0b1220;color:white;padding:14px;border-radius:10px;overflow:auto;white-space:pre-wrap}}
</style></head><body><aside><h2>CH</h2><p>CommerceHub<br>Enterprise V4</p><a href='/'>Dashboard</a><a href='/setup'>Setup</a><a href='/login'>Login</a><a href='/companies'>Empresas</a><a href='/mercado-livre'>Mercado Livre</a><a href='/supabase-test'>Supabase Test</a><a href='/infra-audit'>Infra Audit</a><a href='/connectivity'>Connectivity</a><a href='/vercel-env'>Vercel Env</a><a href='/env-finder'>Env Finder</a><a href='/raw-http'>Raw HTTP</a><a href='/environment'>Environment</a><a href='/database'>Database</a><a href='/core'>Core</a><a href='/logs'>Logs</a><a href='/api/health'>API Health</a></aside><main><h1>{title}</h1>{content}</main></body></html>"""
